[tool.poetry]
name = "pyzaim"
version = "1.0.0"
description = "Zaimのデータを取得・操作するPythonパッケージ"
authors = ["reeve0930 <reeve0930@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
requests-oauthlib = "^1.3.0"
selenium = "^3.141.0"
tqdm = "^4.43.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
